-- ============================================================
-- SEED DATA: 30 mahasiswa acak + nilai + IPK terhitung otomatis
-- Digenerate oleh skrip (seed tetap = 42, hasil selalu sama)
-- ============================================================
USE si_mahasiswa;

-- ---------- Mahasiswa ----------
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220104001', 'Putri Puspita', 'Teknik Informatika', 2.49);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220104002', 'Siti Kusuma', 'Teknik Informatika', 3.32);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220101003', 'Lestari Wijaya', 'Sistem Informasi', 3.25);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220102004', 'Rina Setiawan', 'Teknik Elektro', 3.32);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220102005', 'Ayu Nugroho', 'Sistem Informasi', 2.80);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220101006', 'Nur Pratama', 'Teknik Elektro', 3.08);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220104007', 'Putri Ramadhan', 'Sistem Informasi', 3.18);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220103008', 'Oki Prasetyo', 'Sistem Informasi', 3.51);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220104009', 'Rizky Sari', 'Teknik Sipil', 3.31);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220103010', 'Irfan Firmansyah', 'Teknik Sipil', 3.25);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220103011', 'Siti Firmansyah', 'Teknik Elektro', 3.91);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220103012', 'Siti Setiawan', 'Teknik Sipil', 3.40);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220103013', 'Rizky Halim', 'Sistem Informasi', 2.65);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220103014', 'Ayu Saputra', 'Sistem Informasi', 3.53);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220104015', 'Ayu Prasetyo', 'Teknik Informatika', 3.34);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220105016', 'Maya Rahmawati', 'Sistem Informasi', 3.07);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220105017', 'Siti Utami', 'Teknik Sipil', 3.71);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220103018', 'Ratna Puspita', 'Teknik Informatika', 3.20);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220104019', 'Dimas Saputra', 'Sistem Informasi', 3.69);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220104020', 'Irfan Sari', 'Teknik Informatika', 3.25);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220102021', 'Ayu Kusuma', 'Teknik Mesin', 3.15);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220101022', 'Joko Handayani', 'Teknik Sipil', 1.75);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220102023', 'Lestari Ramadhan', 'Teknik Mesin', 3.08);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220103024', 'Budi Hidayat', 'Teknik Mesin', 2.41);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220105025', 'Fajar Saputra', 'Teknik Informatika', 3.27);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220101026', 'Eko Nugroho', 'Teknik Sipil', 3.53);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220105027', 'Nur Handayani', 'Sistem Informasi', 2.98);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220102028', 'Ayu Santoso', 'Teknik Elektro', 3.04);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220101029', 'Eko Ramadhan', 'Teknik Informatika', 3.11);
INSERT INTO mahasiswa (nim, nama, prodi, ipk) VALUES ('220103030', 'Rizky Puspita', 'Teknik Sipil', 2.97);

-- ---------- Nilai (IPS & IPK dihitung dari sini) ----------
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104001' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104001' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104001' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104001' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104001' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'D', 1.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104001' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104002' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104002' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104002' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104002' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104002' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104002' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104002' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104002' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101003' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101003' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101003' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102004' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102004' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102004' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102004' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102004' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102004' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102005' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'D', 1.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102005' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102005' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102005' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102005' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102005' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102005' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102005' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101006' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101006' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101006' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101006' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101006' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101006' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101006' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101006' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104007' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104007' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104007' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104007' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104007' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104007' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103008' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103008' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103008' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103008' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103008' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103008' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104009' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104009' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104009' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103010' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103010' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103010' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103011' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103011' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103011' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103012' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103012' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103012' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103012' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103012' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103012' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103013' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103013' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103013' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103013' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103013' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103013' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103013' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'D', 1.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103013' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103014' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103014' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103014' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104015' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104015' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104015' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104015' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104015' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104015' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104015' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104015' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105016' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'E', 0.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105016' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105016' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105016' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105016' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105016' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105016' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105016' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105017' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105017' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105017' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105017' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105017' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105017' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103018' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103018' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103018' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103018' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103018' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103018' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103018' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103018' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104019' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104019' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104019' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104020' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104020' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104020' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104020' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104020' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104020' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104020' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220104020' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102021' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102021' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102021' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102021' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102021' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102021' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'D', 1.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101022' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101022' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101022' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102023' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102023' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102023' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102023' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102023' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102023' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102023' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102023' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103024' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'E', 0.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103024' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103024' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103024' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103024' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103024' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'D', 1.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103024' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103024' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105025' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105025' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105025' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105025' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105025' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105025' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105025' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105025' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101026' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101026' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101026' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105027' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105027' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105027' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105027' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105027' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105027' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105027' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B-', 2.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220105027' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102028' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102028' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102028' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102028' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102028' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102028' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102028' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220102028' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101029' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101029' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101029' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101029' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101029' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'B+', 3.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101029' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101029' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220101029' AND mk.kode = 'IF302';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103030' AND mk.kode = 'IF101';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103030' AND mk.kode = 'IF102';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 1, 'B', 3.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103030' AND mk.kode = 'IF103';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C', 2.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103030' AND mk.kode = 'IF201';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'A', 4.00 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103030' AND mk.kode = 'IF202';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 2, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103030' AND mk.kode = 'IF203';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'A-', 3.75 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103030' AND mk.kode = 'IF301';
INSERT INTO nilai (mahasiswa_id, mata_kuliah_id, semester, nilai_huruf, bobot) SELECT m.id, mk.id, 3, 'C+', 2.50 FROM mahasiswa m, mata_kuliah mk WHERE m.nim = '220103030' AND mk.kode = 'IF302';

